use enum_dispatch::enum_dispatch;

use super::*;

#[enum_dispatch(UpdatableExt)]
pub enum Updatables {
    Network,
    Line,
    Substation,
    VoltageLevel,
    Generator,
    Load,
    Bus,
    BusbarSection,
    TwoWindingsTransformer,
    ThreeWindingsTransformer,
    Switch,
    ShuntCompensator,
    StaticVarCompensator,
    DanglingLine,
    TieLine,
    HvdcLine,
    HvdcConverterStation,
    ReactiveCapabilityCurve,
    ReactiveCapabilityCurvePoint,
    MinMaxReactiveLimits,
    ExponentialLoadModel,
    ZipLoadModel,
    BusBreakerTopology,
    NodeBreakerTopology,
    Node,
    InternalConnection,
    RatioTapChanger,
    PhaseTapChanger,
    TapStep,
    PhaseTapStep,
    CurrentLimits,
    TemporaryLimit,
}

pub enum Updaters {
    NetworkUpdater(NetworkUpdater),
    LineUpdater(LineUpdater),
    SubstationUpdater(SubstationUpdater),
    VoltageLevelUpdater(VoltageLevelUpdater),
    GeneratorUpdater(GeneratorUpdater),
    LoadUpdater(LoadUpdater),
    BusUpdater(BusUpdater),
    BusbarSectionUpdater(BusbarSectionUpdater),
    TwoWindingsTransformerUpdater(TwoWindingsTransformerUpdater),
    ThreeWindingsTransformerUpdater(ThreeWindingsTransformerUpdater),
    SwitchUpdater(SwitchUpdater),
    ShuntCompensatorUpdater(ShuntCompensatorUpdater),
    StaticVarCompensatorUpdater(StaticVarCompensatorUpdater),
    DanglingLineUpdater(DanglingLineUpdater),
    TieLineUpdater(TieLineUpdater),
    HvdcLineUpdater(HvdcLineUpdater),
    HvdcConverterStationUpdater(HvdcConverterStationUpdater),
    ReactiveCapabilityCurveUpdater(ReactiveCapabilityCurveUpdater),
    ReactiveCapabilityCurvePointUpdater(ReactiveCapabilityCurvePointUpdater),
    MinMaxReactiveLimitsUpdater(MinMaxReactiveLimitsUpdater),
    ExponentialLoadModelUpdater(ExponentialLoadModelUpdater),
    ZipLoadModelUpdater(ZipLoadModelUpdater),
    BusBreakerTopologyUpdater(BusBreakerTopologyUpdater),
    NodeBreakerTopologyUpdater(NodeBreakerTopologyUpdater),
    NodeUpdater(NodeUpdater),
    InternalConnectionUpdater(InternalConnectionUpdater),
    RatioTapChangerUpdater(RatioTapChangerUpdater),
    PhaseTapChangerUpdater(PhaseTapChangerUpdater),
    TapStepUpdater(TapStepUpdater),
    PhaseTapStepUpdater(PhaseTapStepUpdater),
    CurrentLimitsUpdater(CurrentLimitsUpdater),
    TemporaryLimitUpdater(TemporaryLimitUpdater),
    TerminalRefUpdater(TerminalRefUpdater),
}
